### ISSUE TITLE
The algorithm is not playing the game and just moving in a straight line.

### ISSUE THREAD

**Issue by kishan2k2** [ahmedfgad/FlappyBirdPyGAD#1]
ValueError: In PyGAD 2.20.0, the fitness function must accept 3 parameters:
1) The instance of the 'pygad.GA' class.
2) A solution to calculate its fitness value.
3) The solution's index within the population.

This is the error.

**Comment by ahmedfgad** [comment]
Solved: https://github.com/ahmedfgad/FlappyBirdPyGAD/commit/9e2eaab4dd1b979a5b6f79960763b646864a5a19
